language: csharp
mono: none
dotnet: 3.1.403
install:
 - dotnet restore
 - dotnet add SM.Crawler.Tests/SM.Crawler.Tests.csproj package NUnit.Console --version 3.11.1 --package-directory testrunner
script:
 - msbuild /p:Configuration=Release SM.Crawler.Libs.sln
 - mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./SM.Crawler.Tests/bin/Release/SM.Crawler.Tests.dll